name: Build and Push ARM64 Docker Image

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * *'  # Daily rebuild

env:
  IMAGE_NAME: yourusername/anki-sync-server
  DATE_TAG: $(date +'%Y.%m.%d')

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:pi4-latest
            ${{ env.IMAGE_NAME }}:pi4-${{ env.DATE }}
